# Generated by Django 6.0.3 on 2026-03-06 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('car_model', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=20)),
                ('airport', models.CharField(max_length=200)),
                ('parking_date', models.DateField()),
                ('return_date', models.DateField()),
                ('service_type', models.CharField(choices=[('parking_only', 'Parking Only'), ('parking_wash', 'Parking + Car Wash'), ('parking_interior', 'Parking + Interior Cleaning'), ('parking_ceramic', 'Parking + Ceramic Coating')], max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Car Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('ready', 'Ready For Pickup')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_received', models.BooleanField(default=False)),
                ('exterior_wash', models.BooleanField(default=False)),
                ('interior_clean', models.BooleanField(default=False)),
                ('ceramic_coating', models.BooleanField(default=False)),
                ('ready_for_pickup', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
        ),
    ]
